export const projects = [
  {
    title: 'MERN Memories',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
      image: '/images/1.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'E-Commerce',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'WebRTC App',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/3.jpg',
      tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Unichat',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Took PCM after securing 96.8 % at AISSE', },
  { year: 2018, text: 'Joined Fiitjee Secured 100% Fee Waiver Via Scholarship', },
  { year: 2019, text: 'Secured 91.6% at AISSCE ', },
  { year: 2019, text: 'Started my Majors in Computer Science at Vellore Institute Of Technology ', },
  { year: 2020, text: 'Started with Game-Development', },
  { year: 2020, text: 'Started with ROS', },
  { year: 2020, text: 'Started with Machine Learning', },
  { year: 2021, text: 'Started with Reactjs || Nextjs || React-Native', },
  { year: 2021, text: 'President at SME VIT'},
  {year: 2021, text : 'Intern at METVY.AI in Aritifical Intelligence'},
{year: 2021, text : 'Programming Intern at CoderHalt'},
{year: 2021, text : 'Summer Intern at EdTech in Python '},{year: 2021, text : 'Summer Intern at EdTech in Python '},{year: 2021, text : 'Summer Intern at EdTech in Python '},{year: 2021, text : 'Summer Intern at EdTech in Python '},{year: 2021, text : 'Summer Intern at EdTech in Python ']
